# Generated by Django 6.0.6 on 2026-06-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_listing_featured_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('days', models.PositiveIntegerField(verbose_name='Zile promovare')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preț')),
                ('currency', models.CharField(default='RON', max_length=3, verbose_name='Monedă')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan promovare',
                'verbose_name_plural': 'Planuri promovare',
                'ordering': ['price', 'days'],
            },
        ),
        migrations.CreateModel(
            name='PromotionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('paid', 'Plătită'), ('applied', 'Aplicată'), ('cancelled', 'Anulată')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sumă')),
                ('currency', models.CharField(default='RON', max_length=3, verbose_name='Monedă')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='Referință externă')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_orders', to='listings.listing', verbose_name='Anunț')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.promotionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Comandă promovare',
                'verbose_name_plural': 'Comenzi promovare',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_pro_user_id_0991a3_idx'), models.Index(fields=['status', '-created_at'], name='billing_pro_status_bd3e27_idx')],
            },
        ),
    ]
