# Generated by Django 6.0.6 on 2026-06-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='generic', max_length=50, verbose_name='Provider')),
                ('event_id', models.CharField(max_length=120, verbose_name='ID eveniment')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('received', 'Primit'), ('processed', 'Procesat'), ('ignored', 'Ignorat'), ('failed', 'Eșuat')], default='received', max_length=20, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesat la')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.promotionorder', verbose_name='Comandă')),
            ],
            options={
                'verbose_name': 'Eveniment webhook plată',
                'verbose_name_plural': 'Evenimente webhook plăți',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_pay_provide_7c2dc7_idx'), models.Index(fields=['status', '-created_at'], name='billing_pay_status_b0215a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_payment_event_once')],
            },
        ),
    ]
