# Generated by Django 6.0.6 on 2026-06-13 19:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'În coadă'), ('running', 'Rulează'), ('succeeded', 'Reușit'), ('failed', 'Eșuat')], default='queued', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'run_after', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'run_after'], name='jobs_backgr_status_8f1bf7_idx'), models.Index(fields=['name', 'status'], name='jobs_backgr_name_1fd70e_idx'), models.Index(fields=['locked_at'], name='jobs_backgr_locked__dd098c_idx')],
            },
        ),
    ]
