# Generated by Django 6.0.6 on 2026-06-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_listings_li_status_f5055b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Înșelătorie'), ('prohibited', 'Produs interzis'), ('misleading', 'Informații false'), ('offensive', 'Conținut ofensator'), ('duplicate', 'Anunț duplicat'), ('other', 'Alt motiv')], max_length=30, verbose_name='Motiv')),
                ('details', models.TextField(blank=True, verbose_name='Detalii')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('reviewed', 'Verificat'), ('dismissed', 'Respins'), ('action_taken', 'Acțiune aplicată')], default='pending', max_length=20, verbose_name='Status')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Notă moderator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing', verbose_name='Anunț')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL, verbose_name='Raportat de')),
            ],
            options={
                'verbose_name': 'Raport anunț',
                'verbose_name_plural': 'Rapoarte anunțuri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_li_status_79c206_idx'), models.Index(fields=['listing', 'status'], name='listings_li_listing_723b08_idx'), models.Index(fields=['reporter', '-created_at'], name='listings_li_reporte_8ef341_idx')],
            },
        ),
    ]
