# Generated by Django 6.0.6 on 2026-06-13 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0009_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderation_note',
            field=models.TextField(blank=True, verbose_name='Notă moderare'),
        ),
        migrations.AddField(
            model_name='listing',
            name='needs_moderation_review',
            field=models.BooleanField(default=False, verbose_name='Necesită moderare'),
        ),
        migrations.AddField(
            model_name='listing',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Scor risc'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['needs_moderation_review', '-created_at'], name='listings_li_needs_m_b01180_idx'),
        ),
    ]
