# Generated by Django 6.0.6 on 2026-07-03 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_moderation_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preț final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vândut la')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Cumpărător')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='listings.listing', verbose_name='Anunț')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vânzător')),
            ],
            options={
                'verbose_name': 'Tranzacție anunț',
                'verbose_name_plural': 'Tranzacții anunțuri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', '-created_at'], name='listings_li_seller__69ff97_idx'), models.Index(fields=['buyer', '-created_at'], name='listings_li_buyer_i_8aa0f3_idx')],
            },
        ),
    ]
