# Generated by Django 6.0.6 on 2026-07-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nume')),
                ('prefix', models.CharField(max_length=16, unique=True, verbose_name='Prefix')),
                ('hashed_key', models.CharField(max_length=64, verbose_name='Hash cheie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activă')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creată la')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Folosită ultima dată')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocată la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Cheie API',
                'verbose_name_plural': 'Chei API',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='api_apikey_user_id_90f679_idx')],
            },
        ),
    ]
