# Generated by Django 6.0.6 on 2026-06-13 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('favorites', '0001_initial'),
        ('listings', '0007_listing_featured_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='favorites_f_user_id_3c3f17_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['listing', '-created_at'], name='favorites_f_listing_0d0e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'is_active'], name='favorites_s_user_id_46dd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_active', 'email_notifications'], name='favorites_s_is_acti_df2f6b_idx'),
        ),
    ]
