# Generated by Django 6.0.6 on 2026-07-04 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favorite_favorites_f_user_id_3c3f17_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='last_checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verificat ultima dată'),
        ),
    ]
