# Generated by Django 5.2.5 on 2025-09-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_advanced_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing', verbose_name='Anunț')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Participanți')),
            ],
            options={
                'verbose_name': 'Conversație',
                'verbose_name_plural': 'Conversații',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Trimis la')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversație')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatar')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expeditor')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesaje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/attachments/', verbose_name='Fișier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nume fișier')),
                ('file_type', models.CharField(max_length=50, verbose_name='Tip fișier')),
                ('file_size', models.IntegerField(verbose_name='Dimensiune fișier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Atașament mesaj',
                'verbose_name_plural': 'Atașamente mesaje',
            },
        ),
    ]
