# Generated by Django 6.0.6 on 2026-06-13 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat_messag_receive_14362e_idx_and_more'),
        ('listings', '0007_listing_featured_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['listing', 'is_active'], name='chat_conver_listing_63e9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-updated_at'], name='chat_conver_is_acti_520feb_idx'),
        ),
    ]
