# Generated by Django 6.0.6 on 2026-07-04 14:55

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_chat_conver_listing_63e9f7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=chat.models.private_attachment_storage, upload_to='chat/private/attachments/', verbose_name='Fișier'),
        ),
    ]
