# Generated by Django 5.2.5 on 2025-09-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Descriere')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='Județ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data nașterii')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificat')),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_listings', models.IntegerField(default=0, verbose_name='Total anunțuri')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total vânzări')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating mediu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilizator',
                'verbose_name_plural': 'Profile utilizatori',
            },
        ),
    ]
