# Generated by Django 6.0.6 on 2026-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_note',
            field=models.TextField(blank=True, verbose_name='Notă verificare'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificare cerută la'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificare analizată la'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Neverificat'), ('pending', 'În verificare'), ('verified', 'Verificat'), ('rejected', 'Respins')], default='unverified', max_length=20, verbose_name='Status verificare'),
        ),
    ]
