# Generated by Django 6.0.6 on 2026-06-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_verification_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Înșelătorie'), ('harassment', 'Hărțuire'), ('fake_profile', 'Profil fals'), ('spam', 'Spam'), ('other', 'Alt motiv')], max_length=30, verbose_name='Motiv')),
                ('details', models.TextField(blank=True, verbose_name='Detalii')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('reviewed', 'Verificat'), ('dismissed', 'Respins'), ('action_taken', 'Acțiune aplicată')], default='pending', max_length=20, verbose_name='Status')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Notă moderator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator raportat')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Raportat de')),
            ],
            options={
                'verbose_name': 'Raport utilizator',
                'verbose_name_plural': 'Rapoarte utilizatori',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported_user', 'status'], name='accounts_us_reporte_d51603_idx'), models.Index(fields=['reporter', '-created_at'], name='accounts_us_reporte_360f26_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Motiv')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Strike utilizator',
                'verbose_name_plural': 'Strike-uri utilizatori',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_680077_idx')],
            },
        ),
    ]
