# Generated by Django 6.0.6 on 2026-06-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth.login', 'Login'), ('auth.logout', 'Logout'), ('listing.report', 'Raport anunț'), ('profile.verification_requested', 'Cerere verificare profil'), ('profile.verification_approved', 'Verificare profil aprobată'), ('profile.verification_rejected', 'Verificare profil respinsă'), ('system', 'Sistem')], max_length=80, verbose_name='Tip eveniment')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='Tip obiect')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='ID obiect')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Request ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creat la')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Eveniment audit',
                'verbose_name_plural': 'Evenimente audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='audit_audit_event_t_ff9937_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_fb4253_idx')],
            },
        ),
    ]
