# Generated by Django 6.0.6 on 2026-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('auth.login', 'Login'), ('auth.logout', 'Logout'), ('listing.report', 'Raport anunț'), ('listing.risk_review_required', 'Anunț trimis automat la moderare'), ('listing.moderation_approved', 'Moderare anunț aprobată'), ('listing.moderation_requested', 'Anunț trimis la moderare'), ('listing.promotion_started', 'Promovare anunț pornită'), ('listing.promotion_stopped', 'Promovare anunț oprită'), ('profile.verification_requested', 'Cerere verificare profil'), ('profile.verification_approved', 'Verificare profil aprobată'), ('profile.verification_rejected', 'Verificare profil respinsă'), ('system', 'Sistem')], max_length=80, verbose_name='Tip eveniment'),
        ),
    ]
