# Generated by Django 5.2.5 on 2025-09-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'Mesaj nou'), ('new_review', 'Recenzie nouă'), ('listing_sold', 'Anunț vândut'), ('listing_expired', 'Anunț expirat'), ('listing_approved', 'Anunț aprobat'), ('listing_rejected', 'Anunț respins'), ('price_alert', 'Alertă preț'), ('new_listing_in_category', 'Anunț nou în categorie'), ('account_verification', 'Verificare cont'), ('system', 'Notificare sistem')], max_length=30, verbose_name='Tip notificare')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Tip obiect')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID obiect')),
                ('action_url', models.URLField(blank=True, verbose_name='URL acțiune')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='Trimis pe email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Citit la')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatar')),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificări',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_messages', models.BooleanField(default=True, verbose_name='Email pentru mesaje noi')),
                ('email_new_reviews', models.BooleanField(default=True, verbose_name='Email pentru recenzii noi')),
                ('email_listing_updates', models.BooleanField(default=True, verbose_name='Email pentru actualizări anunțuri')),
                ('email_price_alerts', models.BooleanField(default=True, verbose_name='Email pentru alerte preț')),
                ('email_marketing', models.BooleanField(default=False, verbose_name='Email marketing')),
                ('app_new_messages', models.BooleanField(default=True, verbose_name='Notificare aplicație pentru mesaje')),
                ('app_new_reviews', models.BooleanField(default=True, verbose_name='Notificare aplicație pentru recenzii')),
                ('app_listing_updates', models.BooleanField(default=True, verbose_name='Notificare aplicație pentru anunțuri')),
                ('app_system_updates', models.BooleanField(default=True, verbose_name='Notificare aplicație pentru sistem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Preferință notificare',
                'verbose_name_plural': 'Preferințe notificări',
            },
        ),
    ]
