# Generated by Django 6.0.6 on 2026-06-13 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_recipie_4e3567_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_emailed', 'created_at'], name='notificatio_is_emai_8ec53e_idx'),
        ),
    ]
